-   id: add-license
    name: 'add license'
    entry: run-add-license.sh
    files: '\.go$'
    language: 'script'
-   id: generate-api-docs
    name: 'generate-api-docs'
    entry: run-generate-api-docs.sh
    files: internal/pkg/http/.*\.go
    language: 'script'
    description: "Runs `go-swagger`, requires golang"
-   id: generate-mermaid-diagrams
    name: 'generate-mermaid-diagrams'
    entry: run-generate-mermaid-diagrams.sh
    files: '\.mmd$'
    language: 'script'
    description: "Runs `mermaid.cli`, requires docker"
-   id: go-mod-tidy
    name: 'run go mody tidy'
    entry: run-go-mod-tidy.sh
    files: '\.go$'
    language: 'script'
