-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
      -   id: check-merge-conflict
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
